<?xml version="1.0" encoding="UTF-8"?>

<!-- DTD 구성 -->
<!DOCTYPE scheduleList
[
<!ELEMENT scheduleList (schedule+)>
<!ELEMENT schedule (date, hour, content)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT hour (#PCDATA)>
<!ELEMENT content (#PCDATA)>
<!ATTLIST schedule sid CDATA #REQUIRED>
]>


<scheduleList>
	<schedule sid="1">
		<date><![CDATA[2022-06-27]]></date>
		<hour>9</hour>
		<content>개강</content>
	</schedule>

	<schedule sid="2">
		<date><![CDATA[2022-07-27]]></date>
		<hour>14</hour>
		<content><![CDATA[JAVA Semi-Project]]></content>
	</schedule>

	<schedule sid="3">
		<date><![CDATA[2022-08-30]]></date>
		<hour>9</hour>
		<content><![CDATA[ORACLE Semi-Project]]></content>
	</schedule>
	
	<schedule sid="4">
		<date><![CDATA[2022-10-10]]></date>
		<hour>9</hour>
		<content><![CDATA[Servlet&JSP]]></content>
	</schedule>
	
	<schedule sid="3">
		<date><![CDATA[2023-01-18]]></date>
		<hour>18</hour>
		<content>종강</content>
	</schedule>
	
	
</scheduleList>